apiVersion = "agentic-engineer/v1"
name = "simplest-crud-office"
createdAt = "2026-09-19T08:45:04Z"
idea = "simplest crud office managment. two web apps guest and admin, both share same idp, no api calls other to outside stuff"
