// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "DELETE /assets/{assetId}"
  | "DELETE /guest-accounts/{accountId}"
  | "GET /assets"
  | "GET /guest-accounts"
  | "GET /me/assets"
  | "GET /me/requests"
  | "GET /requests"
  | "POST /assets"
  | "POST /guest-accounts"
  | "POST /me/requests"
  | "PUT /assets/{assetId}"
  | "PUT /guest-accounts/{accountId}"
  | "PUT /requests/{requestId}/status";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "DELETE /assets/{assetId}": { kind: "scope", scope: "assets:manage" },
  "DELETE /guest-accounts/{accountId}": { kind: "scope", scope: "guest-accounts:manage" },
  "GET /assets": { kind: "scope", scope: "assets:read-all" },
  "GET /guest-accounts": { kind: "scope", scope: "guest-accounts:manage" },
  "GET /me/assets": { kind: "scope", scope: "assets:read" },
  "GET /me/requests": { kind: "scope", scope: "requests:read" },
  "GET /requests": { kind: "scope", scope: "requests:read-all" },
  "POST /assets": { kind: "scope", scope: "assets:manage" },
  "POST /guest-accounts": { kind: "scope", scope: "guest-accounts:manage" },
  "POST /me/requests": { kind: "scope", scope: "requests:submit" },
  "PUT /assets/{assetId}": { kind: "scope", scope: "assets:manage" },
  "PUT /guest-accounts/{accountId}": { kind: "scope", scope: "guest-accounts:manage" },
  "PUT /requests/{requestId}/status": { kind: "scope", scope: "requests:manage" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
