// GENERATED by scripts/gen-authz.mjs from specs/design/security.json.
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after the design changes. COMMIT this file: the
// per-component image build cannot see the specs tree.

export type Scope =
  | "assets:manage"
  | "assets:read"
  | "assets:read-all"
  | "guest-accounts:manage"
  | "requests:manage"
  | "requests:read"
  | "requests:read-all"
  | "requests:submit";

export type Role =
  | "Admin"
  | "Guest";

/** Every handle the catalog declares, sorted. */
export const SCOPES: readonly Scope[] = ["assets:manage", "assets:read", "assets:read-all", "guest-accounts:manage", "requests:manage", "requests:read", "requests:read-all", "requests:submit"];

/** Every role a person can hold, sorted. Service-kind roles are not here. */
export const ROLES: readonly Role[] = ["Admin", "Guest"];

/** What each role grants. heldRoles() projects the caller's scopes through this. */
export const ROLE_GRANTS: Record<Role, readonly Scope[]> = {
  "Admin": ["assets:manage", "assets:read-all", "guest-accounts:manage", "requests:manage", "requests:read-all"],
  "Guest": ["assets:read", "requests:read", "requests:submit"],
};

/** The directory groups a role is assigned to — what NoAccess tells a user to ask for. */
export const ROLE_ASSIGN_TO: Record<Role, readonly string[]> = {
  "Admin": ["OfficeAdmins"],
  "Guest": ["OfficeGuests"],
};

/** The roles that can hand this one out — who NoAccess tells a user to ask. */
export const ROLE_ASSIGNABLE_BY: Record<Role, readonly string[]> = {
  "Admin": [],
  "Guest": [],
};

export function isScope(value: string): value is Scope {
  return (SCOPES as readonly string[]).includes(value);
}
